### ISSUE TITLE
Since carbon 2.10.0: The "Add-CIisDefaultDocument" function doesn't exist even though it should. 

### ISSUE THREAD

**Issue by Cyber1000** [webmd-health-services/Carbon#102]
Our deployment-server (octopus) installs the carbon package automatically from powershell gallery. Now with 2.10.0 (since yesterday in powershell gallery) we are getting (reproducible) this bug

```
NotSpecified: Something unexpected happened. The "Add-CIisDefaultDocument" function doesn't exist even though it should. Here are all functions we know about: 
(with a long list, can post if relevant)
```

**Comment by splatteredbits** [comment]
2.10.0 fails to import on PowerShell 4. A fix is coming in the next hour. Sorry!

**Comment by splatteredbits** [comment]
OK. 2.10.1 is out. Let me know if you still have problems.

**Comment by splatteredbits** [comment]
Discovered that 2.10.1 didn't fix the issue, but figured out the root cause: Carbon fails to import if IIS isn't installed. 2.10.2 will fix this, out sometime today.

**Comment by splatteredbits** [comment]
2.10.2 is out. Let me know if you still have an issue.

**Comment by Cyber1000** [comment]
ok we'll try it in the next 2 days.
Thanks for your very fast response!

**Comment by splatteredbits** [comment]
Haven't heard back. Assuming fixed.

**Comment by Cyber1000** [comment]
Yes sorry, used the previous version longer than expected, than vacations, ...
Works for now, thanks for the fix!
