### ISSUE TITLE
IIS functions are not available, but they should be

### ISSUE THREAD

**Issue by montella1507** [webmd-health-services/Carbon#117]
Set-ExecutionPolicy Bypass -Scope Process  -Confirm:$false
Import-Module ServerManager;

If (!$platformInstalled) {
Install-WindowsFeature -name Web-Server -IncludeManagementTools

import-module carbon
Unlock-IisConfigurationSection('system.webServer/security/authentication/windowsAuthentication')
Unlock-IisConfigurationSection('system.webServer/security/authentication/anonymousAuthentication')

The term Unlock-IisConfigurationSection is not recognized as the name of 
a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.

**Any IIS function doesnt work..**

How does Carbon detect installed IIS? Can i disable that  check if it doesnt work correctly?

**Comment by splatteredbits** [comment]
Carbon exports IIS functions if the System.Web.Administration.dll file in C:/Windows/system32/inetsrv. 

What version of Windows? Have you tried opening a new PowerShell window?

**Comment by montella1507** [comment]
Well yeah.. TBH the problem was:

1) importing module carbon
2) installing iis
3) importing module carbon
4) Trying to use IIS functions 

Second import of carbon doesnt import again - even not newly-exported functions...

SO i had to 

import-module carbon -Force after installing IIS.

**Comment by splatteredbits** [comment]
That's what I expected was happening. I would remove the first Carbon. Based on the code you pasted, you don't need Carbon until _after_ you install IIS.

**Comment by montella1507** [comment]
Well, i need for work before IIS installation (working with files with CGetFile etc). So reimporting carbon with -Force is propably the best solution.
