### ISSUE TITLE
Allow modifying group members with Carbon_Group

### ISSUE THREAD

**Issue by qubetzl** [webmd-health-services/Carbon#144]
Hello,

At the moment the `Carbon_Group` DSC resource supports only setting a complete list of members. My request is to have the option to _modify_ (i.e. add or remove) members in an existing group instead of _setting_ them.

My use-case for this is to grant permissions to users managed with DSC by reusing the 'Administrators' and 'Users' groups.
With the current options, I would have to define all members of these groups even if they are not managed with DSC (i.e. the default 'Administrator' user).

I would be happy to discuss the implementation details with you and arrive at a solution that works for both sides.
Would you be willing to accept such functionality and review a PR for it?

**Comment by splatteredbits** [comment]
Have you tried using the builtin `Group` resource? I can't remember why I had to create this resource instead of using the built-in one.

If that doesn't work for you, then please submit a PR with the change. 

Put together a quick design and once we're agreed, you can submit a PR.

We're in the process of breaking Carbon up into smaller, more targeted modules and as part of this we might move the DSC resources into their own `Carbon.DSC` module.

**Comment by qubetzl** [comment]
Yes, I did try it. However, it was spitting back an error relating to server names containing spaces (yes, I know, it sounds _very_ strange).
I did manage to find a bug report about it, which was acknowledged and fixed - https://github.com/PowerShell/PSDscResources/issues/26.

Despite the fix, I was still having trouble and being new to DSC, I started looking for alternatives. This is where Carbon comes in as I had already heard of it my earlier research into DSC. After tinkering with `Carbon_Group` for some time (and realizing it is not fitting my use-case very well) I made this issue.

In the time since then, I stumbled upon https://github.com/dsccommunity/xPSDesiredStateConfiguration, which seems somewhat of a successor of the builtin DSC resources. Its `xGroup` resource does not experience the problem described earlier.

I can cover my use-case with it, however, I still stand by my offer to implement it here, if you think it would be useful to have. It does not seem very complicated to do so.

Here are the two implementation ideas I had in mind:
- Options similar to the ones in the builtin `Group` resource (and `xGroup`).  
Even though it seems like we are reinventing the wheel.
- Option `EnsureMembers` (or something similar), which defines how the `Members` property should be used.  
With allowed values of `Exact`, `Present` and `Absent` with the default of `Exact` to keep the existing behavior.

I like the second option better, because it does not allow you to define an ambiguous set of options i.e. setting all of `MembersToInclude`, `MembersToExclude` and `Members` options. 
If you have a better name for the option - I am all ears. What I have proposed seems somewhat reasonable.

On a separate note, if you have some guidance/pointers/resources to get more involved into DSC they would be greatly appreciated!

**Comment by splatteredbits** [comment]
An `EnsureMembers` property will work. Please proceed.

**Comment by splatteredbits** [comment]
I'm in the process of migrating Carbon's DSC functionality into a new Carbon.DSC module. Once I'm done, any changes to `Carbon_Group` should be made in that repository. I'm awaiting a review from team members. It should be ready tomorrow or Monday, I think.

 https://github.com/webmd-health-services/Carbon.DSC

**Comment by splatteredbits** [comment]
@qubetzl The DSC functionality moved to the Carbon.DSC module. Version 1.0.0 released. Please complete your work over there.

**Comment by qubetzl** [comment]
@splatteredbits Thanks for the heads-up!

I am currently struggling to set up a development environment. I cannot find any instructions about that neither in this, or the new repository. Is there anything you can point me to, that can help me get a development environment going?

What I gathered so far is that I can run the `build.ps1` script in an elevated PS prompt to package the module and get `Pester` to run tests. I assume this is not the most optimal way to do it, because this way it runs all tests each time. There are also test failures occurring in `Initialize-CLcm.Tests.ps1`, which are probably result of something being wrong with my environment. Since they are present without any changes, I think it may be safe for me to just ignore them.

**Comment by splatteredbits** [comment]
@qubetzl Oops. Sorry about that. I'm writing some developer docs now. Here's what I have so far:

> We use [Whiskey](https://github.com/webmd-health-services/Whiskey/wiki) to script our builds. You can find the build
> script in the whiskey.yml file. We use [AppVeyor](https://ci.appveyor.com/project/WebMD-Health-Services/carbon-dsc) to
> run our builds. You can find AppVeyor script in appveyor.yml.
> 
> To get your local environment setup, run `.\build.ps1` from an administrator PowerShll prompt. Once the Pester tests
> start running, you can quit the build or wait for them to finish. A full build should take less than 10 minutes. You can
> check AppVeyor to see current approximate build times. If any tests are failing, reach out to the team to help figure
> out why.
> 
> All code should have tests that are written using Pester 5. We recommend installing a global instance of the Pester 5
> PowerShell module.
>
> When you're developing and testing DSC resources, PowerShell expects the module containing the DSC resources to be in
> the global `PSModulePath` environment variable. Use the `Start-CarbonDscTest.ps1` script to get your machine configured
> so that the Carbon.DSC module you're working on gets added to PowerShell's module path. When you're done developing,
> run `Complete-CarbonDscTest.ps1` to undo this configuration change.  Note that a full build runs both scripts so you'll
> still need to run `Start-CarbonDscTest.ps1` despite running a full build.

Can you send me the output for the failing tests? All tests _should_ pass. They are passing on the build servers. Also let me know what Windows version and what PowerShell edition and version you're using.

**Comment by qubetzl** [comment]
No, worries! I kind of gathered most of that from reading the scripts in the repository root and git history. It is nice that you are putting together development docs for future contributors. Please, also explicitly mention that the steps explained in the last paragraph allow you to run individual test files.

Regarding the test failures, here is the [build.log](https://github.com/user-attachments/files/17109733/build.log) as requested and you will find the version details below. They are more than you have asked for, but the information seemed relevant, so I am including it. The machine I'm working on is a virtual machine running in Virtualbox, so I am not too worried about breaking it.

Since the failures seem to be related to LCM, I've tried running `Set-WsManQuickConfig -SkipNetworkProfileCheck -Force` (and also `Enable-PSRemoting`) to get this solved, but it did not help.


```powershell
PS C:\dev\Carbon.DSC> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.4894
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4894
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```powershell
PS C:\dev\Carbon.DSC> Get-ComputerInfo


WindowsBuildLabEx                                       : 19041.1.amd64fre.vb_release.191206-1406
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
WindowsProductName                                      : Windows 10 Pro
WindowsRegisteredOrganization                           :
WindowsRegisteredOwner                                  : User
WindowsSystemRoot                                       : C:\Windows
WindowsVersion                                          : 2009
CsCaption                                               : DESKTOP-BJNTKCI
CsDNSHostName                                           : DESKTOP-BJNTKCI
CsDomain                                                : WORKGROUP
CsDomainRole                                            : StandaloneWorkstation
CsName                                                  : DESKTOP-BJNTKCI
CsNetworkAdapters                                       : {Ethernet}
CsNetworkServerModeEnabled                              : True
CsPartOfDomain                                          : False
CsRoles                                                 : {LM_Workstation, LM_Server, NT}
CsUserName                                              : DESKTOP-BJNTKCI\User
CsWorkgroup                                             : WORKGROUP
OsName                                                  : Microsoft Windows 10 Pro
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : 48
OsVersion                                               : 10.0.19045
OsCSDVersion                                            :
OsBuildNumber                                           : 19045
OsWindowsDirectory                                      : C:\Windows
OsHardwareAbstractionLayer                              : 10.0.19041.3636
OsOrganization                                          :
OsArchitecture                                          : 64-bit
OsPortableOperatingSystem                               : False
OsPrimary                                               : True
OsProductType                                           : WorkStation
OsServicePackMajorVersion                               : 0
OsServicePackMinorVersion                               : 0
LogonServer                                             : \\DESKTOP-BJNTKCI
HyperVisorPresent                                       : True
DeviceGuardSmartStatus                                  : Off
```

**Comment by qubetzl** [comment]
Forgot to mention details about the steps I took to install the modules needed for `build.ps1`/`Whiskey` to run.
For Pester I followed these [instructions](https://pester.dev/docs/introduction/installation#windows), including the `Removing the built-in version` section.
For everything else I installed multiple versions of the modules side-by-side (AFAIK this is what `-Force` does).

I now recall that installing something warned me about clobbering, but I don't remember what exactly. Maybe that has something to do with the failures. I will try to retrace my steps and note what package it was.

These are the available modules on my system (I've omitted the system32 ones):
```powershell
PS C:\Windows\system32> Get-Module -ListAvailable


    Directory: C:\Users\User\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.15.1     Carbon                              {Add-CGroupMember...
Manifest   2.6.0.0    cChoco
Binary     1.0.5      Microsoft.PowerShell.PSResourceGet  {Find-PSResource,...
Script     9.1.0      xPSDesiredStateConfiguration        {Publish-DscModul...


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0      Carbon.DSC                          {Clear-CDscLocalR...
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationVal...
Script     1.4.8.1    PackageManagement                   {Find-Package, Ge...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Ge...
Script     5.6.1      Pester                              {Invoke-Pester, D...
Script     2.2.5      PowerShellGet                       {Find-Command, Fi...
Script     1.0.0.1    PowerShellGet                       {Install-Module, ...
Script     0.7.0      Prism                               {Invoke-Prism, pr...
Script     2.0.0      PSReadline                          {Get-PSReadLineKe...
```

**Comment by splatteredbits** [comment]
Remoting has to be enabled to configure the LCM. Try running `winrm quickconfig` then run the Initialize-Lcm tests again.

**Comment by splatteredbits** [comment]
In all honesty, I wouldn't spend too much time getting these to work, assuming you're only going to be making changes to the `Carbon_Group` resource. Those tests appear to run successfully on your VM.

**Comment by qubetzl** [comment]
Neither of:
- `winrm quickconfig` with or without forcing it to work on a 'Public' network
- `Set-WsManQuickConfig -Force` with or without forcing it to work on a 'Public' network
- Setting my network to be 'Private'

helped get the tests to pass. When the above mentioned commands don't error about the network type, they suggest that the machine is setup for remote management. I'm am out of ideas as to what to try next.

As we have both mentioned previously, I will just ignore them and work on the `Carbon_Group` resource.
Thank you for looking into anyway!
