### ISSUE TITLE
Grant-CPrivilege pass account name instead of SID

### ISSUE THREAD

**Issue by ig-sinicyn** [webmd-health-services/Carbon#145]
UPD, ny fault. Turns out the adminisrtative panel has the same behavior as the Grant-CPrivilege command

Previous version:
Carbon v2.15.1

The `Grant-CPrivilege` command passes user name instead of user's sid.

Add privelege:
```
if (Get-Module -ListAvailable Carbon) {
    Import-Module Carbon
}
else {
    Install-Module Carbon -MinimumVersion 2.15.1 -Force
}

$accountName = 'SomeUser'
Grant-CPrivilege -Identity $accountName 'SeServiceLogonRight'
```

Check:
```
$seceditDump = "$env:tmp\secedit.dump.inf"
secedit /export /cfg $seceditDump
cat $seceditDump
```

the dump contains something like
```
SeServiceLogonRight = SomeUser,*S-1-5-80-0,*S-1-5-....
```
but should have contain user's SID

**Comment by splatteredbits** [comment]
ℹ️ Privilege management functions are now in the [Carbon.Security module](https://github.com/webmd-health-services/Carbon.Security/releases), [available on the PowerShell Gallery](https://www.powershellgallery.com/packages/Carbon.Security).
