### ISSUE TITLE
Problem with aliases in 2.7.0

### ISSUE THREAD

**Issue by kjsmithtx** [webmd-health-services/Carbon#55]
There are a couple of problems with this latest release. The Get-WindowsFeature.ps1, Install-WindowsFeature.ps1, and Uninstall-WindowsFeature.ps1 scripts were changed to check for Get-CWindowsFeature* before they create that function, but that is wrong. You should still be checking for Get-WindowsFeature* as that is the thing you are trying to simulate if not available. Also, since you are creating aliases for all of the functions listed in Carbon.psd1, you are effectively not solving the original problem of not clobbering existing functions. I have made changes to my local copy and attached them  if you would like to review them for inclusion. I think the idea of aliasing the renamed functions is a mistake that you should look at hard for the next release.  I would not alias and note that the release causes breaking changes.  Another approach would be to allow for aliases with a switch of some kind, but I feel that should be a stop-gap measure as the sooner you get totally away from name collisions the better.
[Carbon_Updates.zip](https://github.com/webmd-health-services/Carbon/files/2746293/Carbon_Updates.zip)

**Comment by splatteredbits** [comment]
Thank you for the feedback!

Now that the functions have new names, I think I can actually remove the optional export of those functions. To address your issue, I'll conditionally create the new aliases.

I really value backwards-compatibility and easy upgrades. I want to require the minimal amount of code changes for people wanting to upgrade. I'm not sure what I'm going to do for the next major version.

**Comment by splatteredbits** [comment]
Fixed in Carbon 2.9.0-rc587, now available on the [PowerShell Gallery](https://www.powershellgallery.com/packages/Carbon/2.9.0-rc587) and [GitHub](https://github.com/webmd-health-services/Carbon/releases/tag/2.9.0-rc587). Please takea  few minutes to download and test that your issue is fixed. We'll be publishing the final version of 2.9.0 Wednesday or Thursday.

**Comment by splatteredbits** [comment]
2.9.0 is out.
