### ISSUE TITLE
Functionname Set-EnvironmentVariable conflicts with Chocolatey

### ISSUE THREAD

**Issue by KurtTheBerner** [webmd-health-services/Carbon#77]
If importing Carbon within a Chocolatey installChocolatey.ps1 Script, the Chocolatey Function
`Install-ChocolateyEnvironmentVariable` uses a Function `Set-EnvironmentVariable`, which conflicts with the Carbon Function.

Errormessage:
`ERROR: A parameter cannot be found that matches parameter name 'Scope'.`

Carbon overrides the the Chocolatey Function Set-EnvironmentVariable which causes the Error.

**Comment by splatteredbits** [comment]
There's nothing I can do about this in the current version of Carbon. This problem will go away in the next major version, as all Carbon functions will be renamed with a `C` prefix.
