### ISSUE TITLE
Cannot review my new commit

### ISSUE THREAD

**Issue by oliwex** [webmd-health-services/Carbon#79]
Logs from AppVeyor:

[00:02:59.25]  [PowerShell]  .\Start-CarbonTest.ps1
The term 'ï»¿' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  at <ScriptBlock>, C:\projects\carbon\Carbon\Carbon.psm1: line 2725
  at <ScriptBlock>, C:\projects\carbon\Carbon\Import-Carbon.ps1: line 64
  at <ScriptBlock>, C:\projects\carbon\Carbon\Import-Carbon.ps1: line 44
  at <ScriptBlock>, C:\projects\carbon\Start-CarbonTest.ps1: line 28
  at <ScriptBlock>, <No file>: line 82
    + CategoryInfo          : ObjectNotFound: (ï»¿:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost
 
The module to process 'Carbon.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\projects\carbon\Carbon\Carbon.psd1' was not processed because no valid module was found in any module directory.
  at <ScriptBlock>, C:\projects\carbon\Carbon\Import-Carbon.ps1: line 64
  at <ScriptBlock>, C:\projects\carbon\Carbon\Import-Carbon.ps1: line 44
  at <ScriptBlock>, C:\projects\carbon\Start-CarbonTest.ps1: line 28
  at <ScriptBlock>, <No file>: line 82
    + CategoryInfo          : ResourceUnavailable: (Carbon:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
    + PSComputerName        : localhost
 
C:\projects\carbon\Start-CarbonTest.ps1 : The term 'Get-PowerShellModuleInstallPath' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
  at <ScriptBlock>, C:\projects\carbon\Start-CarbonTest.ps1: line 30
  at <ScriptBlock>, <No file>: line 82
    + CategoryInfo          : ObjectNotFound: (Get-PowerShellModuleInstallPath:String) [Start-CarbonTest.ps1], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Start-CarbonTest.ps1
 
  at Write-WhiskeyInfo<End>, C:\projects\carbon\PSModules\Whiskey\0.44.0\Whiskey.psm1: line 6731
  at Write-WhiskeyError<End>, C:\projects\carbon\PSModules\Whiskey\0.44.0\Whiskey.psm1: line 6591
  at <ScriptBlock>, <No file>: line 88
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-WhiskeyInfo
    + PSComputerName        : localhost
 
VERBOSE: [00:02:59.91]  [PowerShell]  Exit Code  0
VERBOSE: [00:02:59.92]  [PowerShell]  $?         False
VERBOSE: [00:02:59.98]  [PowerShell]  FAILED in 00:00:02.4139742
VERBOSE: [00:02:59.98]  [PowerShell]  
VERBOSE: [00:02:59.99]  [PowerShell]  FAILED in 00:00:03.9679738
VERBOSE: [00:02:59.99]  [PowerShell]  
Uploading artifact appveyor_APPVYR-WIN_2020-01-05_21_01_33.trx (54,083 bytes)...100%
Uploading artifact dotnet.publish.Carbon.Test.csproj.log (951,410 bytes)...100%
Uploading artifact dotnet.test.Carbon.Test.csproj.log (157,583 bytes)...100%
Uploading artifact msbuild.Carbon.csproj.log (390,764 bytes)...100%
Uploading artifact msbuild.Carbon.Iis.csproj.log (388,170 bytes)...100%
Uploading artifact msbuild.Carbon.sln.log (3,637,192 bytes)...100%
Uploading artifact msbuild.Carbon.Xdt.csproj.log (380,528 bytes)...100%
Uploading artifact nunit3+uvlq5egf.2fj.xml (33,668 bytes)...100%
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\projects\carbon\whiskey.yml: Task "PowerShell": PowerShell script ".\Start-CarbonTest.ps1" threw a terminating exception.

**Comment by splatteredbits** [comment]
Looks like there is a byte-order mark at the beginning of one of your new files. Make sure the files are encoded as UTF8 without BOM.
