### ISSUE TITLE
Carbon.dll is missing

### ISSUE THREAD

**Issue by garryoneill** [webmd-health-services/Carbon#93]
Hello, 

It appears the carbon.dll is missing from the PowerShell module. 

When I run Get-CPrivilege command I get the following error. 
```
PS C:\windows\system32> Get-CPrivilege test
Unable to find type [Carbon.Security.Privilege].
At E:\Downloads\Carbon-develop\Carbon-develop\Carbon\Functions\Get-Privilege.ps1:45 char:5
+     [Carbon.Security.Privilege]::GetPrivileges( $Identity )
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Carbon.Security.Privilege:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

Searching through the folders I can see there is no "carbon.dll" to be found. 

Thanks
Garry

**Comment by splatteredbits** [comment]
What version of Carbon? How did you download/install it?

**Comment by garryoneill** [comment]
Sorry by bad. I download the zip file from github. Installing it using the Gallery works.

**Comment by splatteredbits** [comment]
We may have a corrupt .zip file. What version did you download? You can look in the .zip file at Carbon\Carbon.psd1.

**Comment by garryoneill** [comment]
I downloaded it straight from the 'code' page from your github. Module version is '2.9.4'

**Comment by splatteredbits** [comment]
Ah. Downloading the code won't get you a functional module. You'd have to build it first. Instead, download an already built package from the [Releases page](../releases), or, as you discovered, use `Install-Module` or `Save-Module`.
